### ISSUE TITLE
Row/Column data for FrameManipulation functions

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#13]
As I'm about to work on a function, I realized I dont have access to R/C sizes at that point in the file.

There are 3 solutions I can think of:

1) Provide r/c to every function: fillFrame(t_FrameData F, int r, int c)
Pro: Flexible, explit
Con: Much More typing. Possibly less flexible in some situations

2) We can have r/c global and extern them to the FrameManipulation file
Pro: No extra typing
Con: Not only is it global but it is also externed to other files.
        Less flexible

3) We can include r/c in the FrameData itself
Pro: Easy, no extra typing. Easily referable, flexible
Con: Adds two more ints to EVERY frame
       One mitigation to the Con is that we are looking at max frame sizes specification of under 20x20. So we can use shorts or U_chars which would give us up to 256x256 frame size for this.
Only 2kb per 1000 nodes extra memory

**Comment by tsonnen** [comment]
I added in a partial fix within the FrameList class
I just added in a get function for the row and column
```
/* Get the row count */
int FrameList::GetRowCount(){
    return this->row;
}

/* Get the column count */
int FrameList::GetColCount(){
    return this->col;
}
```

**Comment by Cyberzoid1** [comment]
I like this Idea,but... functions in fileManipulation like fillFrame, copyFrame has nothing to do with FrameList.
They don't even have any access to FrameList.

Still those methods will be useful later in other areas.

**Comment by Kevin-Dorscher** [comment]
You added in counter manipulation too which is something that I was going to bring up in the meeting tonight as well as the memory leak for the RGB structures. The DeleteNode function can actually be deleted entriely as DeleteNode_Middle covers all cases DeleteNode_Middle(0) would delete the head of the list, and DeleteNode_Middle(count - 1) would delete the tail, ect. I will ask a few things tonight in the group meeting to fix some of these issues.

**Comment by Cyberzoid1** [comment]
"Counter manipulation?" Are you refering to Frame order?
Frame order is just the order they appear in the FrameList.

**Comment by tsonnen** [comment]
I think that what @Mr-Triangle (Kevin) means is the changing of the count variable for the FrameList object

**Comment by Kevin-Dorscher** [comment]
Right by counter manipulation, I just meant that the counter that holds the number of nodes we have in our linked list should be incrimented whenever a new node is added, and decrimented everytime a node is deleted. I just did the basic structure for Add / Delete at position x because there was a few things I wanted to clear up before changing some other things, that I felt would be easier to explain in the group meeting tonight.

**Comment by Cyberzoid1** [comment]
Solution 3 picked and implemented in commit:
https://github.com/CS383Team2/Goofy_Lights_Editor/commit/3d7f5a74d92db2e36ecbae42223e245ade6951c7
