### ISSUE TITLE
File Questions

### ISSUE THREAD

**Issue by tsonnen** [CS383Team2/Goofy_Lights_Editor#17]
If we are getting the duration by comparing the assumed start and end time, we are left with an issue of calculating the duration of the last frame as there is no end time present. 
Do we simply want to append what the end time would be within the *.tan file?
```
00:00.000				// Frame 1 start time
0 0 0 0 0 0 0 0 0 0 0 0 		// frame 1 data
...
...
0 0 0 0 0 0 0 0 0 0 0 0
00:00.500						// frame 2 start. Frame 1 end
255 0 0 0 0 0 0 ....			               // frame 2 data

// If frame 2 is the last frame, there is no time present 
// as to when we should stop showing it.
```

Also, is there any special information that we should include in the custom pallet portion of the *.tan file?

**Comment by Cyberzoid1** [comment]
I suppose that's an end case. We can always assume that the last frame is infinite duration. 

Even before this, what would happen when the last frame runs past its duration? Do we just keep the last frame up?

**Comment by Kevin-Dorscher** [comment]
Rinker said we could completely eliminate the "custom pallet" portion of the .tan file as it was not needed, but if everyone else wanted to add some custom colors in at that point in the file, thats good with me.

**Comment by tsonnen** [comment]
Okay. I will exclude it for now, but I do not think that it would be an issue to add it in if we decide we want custom palette in the future.

**Comment by Cyberzoid1** [comment]
@tsonnen Is this still a question? or can it be closed?

**Comment by tsonnen** [comment]
Closed
