### ISSUE TITLE
SearchNode_Middle Question

### ISSUE THREAD

**Issue by Kevin-Dorscher** [CS383Team2/Goofy_Lights_Editor#18]
So, I have completed all of the linked list functions, but have not committed anything to master yet. I have a question, as this is not something I was able to get working previously. This is also why I didn't initally want to return pointers from some of the Linked List functions.

For the search list function, there are a few cases where A node being searched for is not found. or cannot be found because it does not exist. My question is how do I return NULL from the fucntion, without an error? Here is the code for the function:

```
t_FrameData FrameList::RetrieveNode_Middle(int pos){
	int tempCount = 0;
	t_FrameData x;
	NodePtr temp = head;
	
	if (pos == 0)
	{
		// return pointer to the head node's FrameData.
		if (head == NULL)
		{
			// no pointer to return Error.
                       return ???;
		}
		else
		{
			x = head -> FrameData;
			return x;
		}
	}
	else
	{
		tempCount++;
		temp = temp -> next;
		while (tempCount != pos)
		{
			tempCount++;
			temp = temp -> next;
		}
			
		if (temp != NULL)
		{
			// Just checking to make sure no bounds have been crossed.
			x = temp -> FrameData;
			return x;	
		}
		else
		{
                        return ???;
		}
	}
} 
```

NOTE:
I have tried the following options, but none of them have worked

(t_FrameData) x = NULL;
return x;

return NULL:

return nullptr;

// I knew this wouldn't work but I gave it a shot anyway
return 0;

**Comment by Cyberzoid1** [comment]
So instead of retuning a FrameData variable it shoud return a FrameData pointer. Then the code calling the search function needs to check if the returned value is NULL.

This will likely need to change for all methods retuning a t_FrameData

`t_FrameData * FrameList::RetrieveNode_Middle(int pos){`

**Comment by Cyberzoid1** [comment]
Related to #4 as well and possibly #5

**Comment by Kevin-Dorscher** [comment]
haha oh duhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by Kevin-Dorscher** [comment]
I kept thinking reutrning a NULL pointer is legal, but missed the * haha

**Comment by Kevin-Dorscher** [comment]
that fixed the issue, will update master here in a minute. Thanks, Nick
