### ISSUE TITLE
Click and drag to draw

### ISSUE THREAD

**Issue by YupHio** [CS383Team2/Goofy_Lights_Editor#21]
If anyone wants to dip into Qt, this is a very simple feature to implement. Currently each cell has to be clicked individually to change its color. We want to be able to click and drag across multiple cells. Make it happen.

**Comment by welc2421** [comment]
I'll start working on this this afternoon

**Comment by YupHio** [comment]
This one sucks. Hard to implement as it turns out. Lol

**Comment by Cyberzoid1** [comment]
A draw rectangle was implemented using the last 2 points changed
