### ISSUE TITLE
Doc: Add Current GUI screenshots

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#25]
Add screenshots of current program to the Master tex document.

Filenames should be clear like `screenshot_name`

For updates we will overwrite screenshot file then recompile the letex doc.

**Comment by Kevin-Dorscher** [comment]
I can add this in I believe I have the old template from last semesters project, as well as our first "blank" GUI and the newest version.

**Comment by Kevin-Dorscher** [comment]
See PR #29 for more info, should be done, just need to recompile the PDF...

**Comment by Cyberzoid1** [comment]
For on campus, i use the portable version of protex. I keep it on my userdrive so that I can access whenever.
Protex comes with texstudio.

**Comment by Kevin-Dorscher** [comment]
ok I knew there was some online editors I could use also, but i don't know of any that would allow me to access this repo directly.

**Comment by Cyberzoid1** [comment]
Ya I was already thinking about doing a travisCI integration and create a makefile for the tex document.

And/OR just have it monitor for commits on the master.tex file then compile the document.

In short you could use an online one but it would break since the document links to all the source files, UML diagrams, and screenshots
