### ISSUE TITLE
FrameList Delete node x

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#3]
`FrameList::DeleteNode(int position)`

We can either write a new method or change the functionality of existing DeleteNode()

**Comment by Kevin-Dorscher** [comment]
I am still planning on creating new functions for both of these, though we could alter / delete the existing DeleteNode function. If we can already delete a node at any position then the only case left woud be to delete all nodes for project termination.

**Comment by Cyberzoid1** [comment]
ya DeleteEnd maybe common depending on the user but that use case can probably be covered by a position number.

What ever frame the user is working with they will know the frame number.

However I would vote to keep the delete end method and write a new method for deleting a mid node. 
Gives us more flexability

**Comment by Kevin-Dorscher** [comment]
yeah thats good with me, I can always add some smaller cases / functions as we feel they are needed.

**Comment by Kevin-Dorscher** [comment]
Adjusted previous pointers, so this function is good to go.

**Comment by Cyberzoid1** [comment]
When you feel that this issue is done feel free to close it after its been tested

**Comment by Kevin-Dorscher** [comment]
I will, I have already tested AddNode_Middle and DeleteNode_Middle after the adjustments to the previous pointers, and they are good to go, so i'll close both issues and finish up patching the SearchNode_Middle function and test and close that issue as well.

**Comment by Cyberzoid1** [comment]
For something this big and complex, you really should be working in a separate branch until your branch is stable instead of pushing directly to master.

Its a better flow model
