### ISSUE TITLE
Color sampler

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#32]
Much like how you can sample a color in MS paint, we should implement a feature where we can grab a color in a square and apply it to the current color pallet.

**Comment by welc2421** [comment]
I'll work on this. I will combine it with recent colors if that is ok.

**Comment by Cyberzoid1** [comment]
What do you mean by combine with recent colors?

**Comment by welc2421** [comment]
I just meant I was doing both lol

Sent from my iPhone

On Apr 8, 2017, at 11:42 AM, Nick <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you mean by combine with recent colors?

**Comment by welc2421** [comment]
I don't know what I was thinking. I have the preview done but I am still working on recent colors.
