### ISSUE TITLE
FrameList Retrieve Frame x

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#4]
`t_FrameData GetNode(int position)`

Returns FrameData from a Node in x position

**Comment by Kevin-Dorscher** [comment]
Finished the bulk of the work for this function, see Issue #18 for small fix before it is committed to master.

**Comment by Kevin-Dorscher** [comment]
Function completed, tested and working correctly closing this "To Do" item.
