### ISSUE TITLE
Issue with diagonal translations on timeline

### ISSUE THREAD

**Issue by gjcarter** [CS383Team2/Goofy_Lights_Editor#43]
There is a bug where there seems to be an extra row and column opposite of the direction you are translating diagonally. This can be seen in the attached picture where I'm translating a frame up and to the right 5 times.
![image](https://cloud.githubusercontent.com/assets/26151391/25260292/1890c8ac-2600-11e7-9c8d-6e329613d63f.png)

**Comment by gjcarter** [comment]
After some testing, seems it is related to the click lag on the timeline. Clicking on the timeline after a translation puts it in the correct place.

**Comment by Cyberzoid1** [comment]
Is this still the case after Pauls timeline lag fix?

**Comment by gjcarter** [comment]
Yes. This bug persists after Paul's fix.

**Comment by gjcarter** [comment]
This bug is fixed.
