### ISSUE TITLE
Top bottom rows swapped after up/down translation

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#45]
I had to revert commit https://github.com/CS383Team2/Goofy_Lights_Editor/commit/19949969513262b7a22c44d13bbab46e1d13ad0b
since the new code is now segfaulting since the merge
This reintroduces the top and bottom rows being swapped after a up/down transition

**Comment by gjcarter** [comment]
This should be fixed with the change I made.
