### ISSUE TITLE
Function CopyFrame

### ISSUE THREAD

**Issue by Cyberzoid1** [CS383Team2/Goofy_Lights_Editor#9]
`t_FrameData copyFrame(t_FrameData FrameData)`

This function is passed a frame that is to be copied. The function would create a FrameData array then copy the origional frame and return a pointer to the new frame.

**Comment by YupHio** [comment]
I volunteer as tribute

**Comment by Cyberzoid1** [comment]
Done last night

**Comment by Cyberzoid1** [comment]
New interface `int copyFrame(t_FrameData &copyFrame, t_FrameData origFrame);`
